### ISSUE TITLE
plugins.cordova.io will be deprecated in the near future

### ISSUE THREAD

**Issue by bau720123** [macdonst/TelephoneNumberPlugin#12]
according to this
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

so...just want to inform you that your plugin should be move to npm in the future...

**Comment by Heshyo** [comment]
The following plugin is on npm. It's more generic than just phone number. It should have the same limitations as this plugin: https://www.npmjs.com/package/cordova-plugin-sim

**Comment by bau720123** [comment]
hi @Heshyo 
thanks your reply
I have already know this plugin on npm before
thanks again
