### ISSUE TITLE
Error in ios

### ISSUE THREAD

**Issue by ericfong** [macdonst/TelephoneNumberPlugin#8]
Got 

ERROR: Plugin 'TelephoneNumber' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.

and 

[CDVCommandQueue executePending] [Line 158] FAILED pluginJSON = [
  "TelephoneNumber529414938",
  "TelephoneNumber",
  "get",
  [

  ]
]

When I try to get phone number in ios simulator. It stops the whole program.
I wrapped the get function in try and catch block, still cannot prevent the Error.

Anyway to work around that. 

Sorry for my bad english and Thanks

**Comment by dbaq** [comment]
hey @ericfong, this plugin works only for android, it's not compatible with iOS.

**Comment by ericfong** [comment]
Oh. Thanks
